blank_issues_enabled: false
contact_links:
  - name: GLPI Community Forum
    url: https://forum.glpi-project.org
    about: Ask questions and get help from the community.
    about: Get professionnal support from the editor and a network of local partners.
  - name: Feature request
    url: https://suggest.glpi-project.org
    about: Suggest a new feature to the GLPI team
